<div class="page-header">
    <h1><?php eh($titulo) ?></h1>
</div>
<div class="row">
    <div class="span3">
        <?php View::partial('backend/menus/tipo_solicitud') ?>
    </div>
    <div class="span8 span-derecho" >
        <div id="res-form-ajax"><?php View::content() ?></div>
        <?php echo Ajax::form('res-form-ajax', NULL, 'form-horizontal') ?>
        <?php //echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
        <?php echo Form::hidden('tipo_solicitud.id') ?>
        <div class="row control-group">
            <label class="control-label" for="tipo_solicitud_nombre">Nombre * : </label>
            <?php echo Form::text('tipo_solicitud.nombre', 'class="span4"') ?>
        </div>
        <div class="row control-group">
            <label class="control-label" for="tipo_solicitud_observacion">Observación * : </label>
            <?php echo Form::textarea('tipo_solicitud.observacion', 'class="span4"') ?>
        </div>
            <div class="form-actions">
            <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
            <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
            </div>
        <?php echo Form::close() ?>
    </div>
</div>
