<div class="page-header">
    <h1>Crear Empleado</h1>
</div>
<div class="row">
    <div class="span3">
        <?php View::partial('backend/menus/empleado') ?>
    </div>
    <div class="span8 span-derecho" >
        <div id="res-form-ajax"><?php View::content() ?></div>
        <?php echo Ajax::form('res-form-ajax', NULL, 'form-horizontal') ?>
        <?php //echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
        <?php echo Form::hidden('empleado.id') ?>
        <div class="control-group">
            <label class="control-label" for="empleado_persona_id">Persona_ID* : </label>
            <div class="controls">
                <?php echo Form::text('empleado.persona_id') ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="empleado_cargo_id">Cargo_ID* : </label>
            <div class="controls">
                <?php echo Form::dbSelect('empleado.cargo_id', 'nombre', array('cargo', 'find'), 'Ninguno') ?>
            </div>
        </div>
            <div class="form-actions">
            <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
            <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
                    </div>
        <?php echo Form::close() ?>
    </div>
</div>
