<div class="page-header">
    <h1>Crear Empleado</h1>
</div>
<div class="row">
    <div class="span3">
        <?php View::partial('backend/menus/empleado') ?>
    </div>
    <div class="span8 span-derecho" >
        <div id="res-form-ajax"><?php View::content() ?></div>
        <?php echo Ajax::form('res-form-ajax', NULL, 'form-horizontal') ?>
        <?php //echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
        <?php echo Form::hidden('empleado.id') ?>
        <div class="hero-unit">
            <div class="page-header">
            <h3>Datos Personales <small>* Campos Requeridos </small></h3>
            </div>
                <div class="row ">
                    <div class="span2">
                        <label for="persona_cedula"><b>Cedula * :  </b></label>
                    </div>
                    <div class="span2">
                        <label  for="persona_nombre1"><b>Primer Nombre * : </b></label>
                    </div>
                    <div class="span2">
                        <label class="control-label" for="persona_nombre2">Segundo Nombre  :  </label>
                    </div>

                </div>

                <div class="row control-group">
                    <div class="span2">
                        <?php echo Form::text('persona.cedula', 'class="span2"') ?>
                    </div>
                    <div class="span2">
                        <?php echo Form::text('persona.nombre1', 'class="span2"') ?>
                    </div>
                    <div class="span2">
                        <?php echo Form::text('persona.nombre2', 'class="span2"') ?>
                    </div>
                </div>

                <div class="row ">
                    <div class="span2">
                        <label  for="persona_apellido1"><b>Primer Apellido * : </b></label>
                    </div>
                    <div class="span2">
                        <label  for="persona_apellido2">Segundo Apellido  :  </label>
                    </div>
                    <div class="span2">
                        <label  for="persona_fecha_nacimiento"><b>Fecha de Nacimiento * : </b></label>
                    </div>
                </div>

                <div class="row control-group">
                    <div class="span2">
                        <?php echo Form::text('persona.apellido1', 'class="span2"') ?>
                    </div>
                    <div class="span2">
                        <?php echo Form::text('persona.apellido2', 'class="span2"') ?>
                    </div>
                    <div class="span2">
                        <?php echo Form::date('persona.fecha_nacimiento', 'class="span2"') ?>
                    </div>
                </div>
                <div class="row ">
                    <div class="span2">
                        <label  for="persona_telefono_local"><b>Telefono Local * :  </b></label>
                    </div>
                    <div class="span2">
                        <label  for="persona_telefono_movil"><b>Telefono Movil * : </b></label>
                    </div>
                    <div class="span2">
                        <label  for="persona_direccion"><b>Dirección * :  </b></label>
                    </div>
                </div>
                
                <div class="row control-group">        
                    <div class="span2">
                        <?php echo Form::text('persona.telefono_local', 'class="span2"') ?>
                    </div>
                    <div class="span2">
                        <?php echo Form::text('persona.telefono_movil', 'class="span2"') ?>
                    </div>
                    <div class="span2">
                        <?php echo Form::textarea('persona.direccion', 'class="span3"') ?>
                    </div>
                </div>

            <div class="page-header">
                <h3>Datos Laborales <small>* Campos Requeridos </small></h3>
            </div>
                <div class="row ">
                    <div class="span2">
                        <label  for="persona_telefono_local"><b>Cargo * :  </b></label>
                    </div>
                    <div class="span2">
                    <p> </p>
                    </div>
                </div>
                
                <div class="row control-group">        
                    <div class="span2">
                        <?php echo Form::dbSelect('empleado.cargo_id', 'nombre', array('cargo', 'find'), 'Ninguno') ?>
                    </div>
                    <div class="span2">
                        <p> </p>
                    </div>
                </div>
        </div><!--aqui va final apan hero -->   

            <div class="form-actions">
                <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
                <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
            </div>
        <?php echo Form::close() ?>
    </div>
</div>
