<div class="page-header">
    <h1>Empleados</h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div> 
<?php
    View::partial('backend/barra_superior_listas', FALSE, array('texto' => 'Crear Empleado', 'opciones' => FALSE));
    $dt = new DataTable($empleado);
    $dt->addHeaders('id', 'Persona', 'Cargo', 'Estado', 'Editar');
    $dt->addFields('id', 'persona_id', 'cargo_id');
    $dt->imgLink('figuras/circulo_rojo.png|figuras/circulo_verde.png',
            'admin/usuarios/activar|admin/usuarios/desactivar', '', 'activo');
    $dt->imgLink('figuras/editar.png', 'admin/usuarios/editar');
    echo $dt->render('class="table table-bordered table-striped"');
?>
