<div class="page-header">
    <h1>Empleados</h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div> 
<?php
    View::partial('backend/barra_superior_listas', FALSE, array('texto' => 'Crear Empleado', 'opciones' => FALSE));
    $dt = new DataTable($empleado);
    $dt->addHeaders('id', 'Nombre', 'Apellido' ,'Cargo', 'Estado', 'Editar');
    $dt->addFields('id', 'nombre1', 'apellido1', 'nombre');
    $dt->imgLink('figuras/circulo_rojo.png|figuras/circulo_verde.png',
            'admin/empleado/activar|admin/empleado/desactivar', '', 'activo');
    $dt->imgLink('figuras/editar.png', 'admin/empleado/editar');
    echo $dt->render('class="table table-bordered table-striped"');
?>
