<div class="page-header">
    <h1>Planificación</h1>
</div>
<?php View::content() ?>
<?php
echo ". ";/*

echo Form::open('admin/cargo/eliminar', 'post', 'class="form_lista"');
View::partial('backend/barra_superior_listas', FALSE, array('texto' => 'Crear Cargo'));
$dt = new DataTable($cargos);
$dt->addHeaders(Form::check('seleccionar_todos', 'todos', NULL, FALSE));
$dt->addHeaders('id', 'Nombre', 'Observación');
$dt->addHeaders('Editar', 'Eliminar');
$dt->check('cargo_id');
$dt->addFields('id', 'nombre', 'observacion');
$dt->imgLink('figuras/editar.png', 'admin/cargo/editar');
$dt->imgLinkConfirm('figuras/eliminar.png', 'admin/cargo/eliminar', '', '¿Realmente desea Eliminar Este Cargo?');
echo $dt->render('class="table table-bordered table-striped"');
echo Form::close();
*/

?>

<script>

	$(document).ready(function() {

		$('#calendar').fullCalendar({
			defaultDate: '2014-09-12',
			editable: true,
			eventLimit: true, // allow "more" link when too many events
			events: [
				{
					title: 'All Day Event',
					start: '2014-09-01'
				},
				{
					title: 'Long Event',
					start: '2014-09-07',
					end: '2014-09-10'
				},
				{
					id: 999,
					title: 'Repeating Event',
					start: '2014-09-09T16:00:00'
				},
				{
					id: 999,
					title: 'Repeating Event',
					start: '2014-09-16T16:00:00'
				},
				{
					title: 'Conference',
					start: '2014-09-11',
					end: '2014-09-13'
				},
				{
					title: 'Meeting',
					start: '2014-09-12T10:30:00',
					end: '2014-09-12T12:30:00'
				},
				{
					title: 'Lunch',
					start: '2014-09-12T12:00:00'
				},
				{
					title: 'Meeting',
					start: '2014-09-12T14:30:00'
				},
				{
					title: 'Happy Hour',
					start: '2014-09-12T17:30:00'
				},
				{
					title: 'Dinner',
					start: '2014-09-12T20:00:00'
				},
				{
					title: 'Birthday Party',
					start: '2014-09-13T07:00:00'
				},
				{
					title: 'Click for Google',
					url: 'http://google.com/',
					start: '2014-09-28'
				}
			]
		});
		
	});

</script>
<style>

	body {
		margin: 40px 10px;
		padding: 0;
		font-family: "Lucida Grande",Helvetica,Arial,Verdana,sans-serif;
		font-size: 14px;
	}

	#calendar {
		max-width: 900px;
		margin: 0 auto;
	}

</style>
<body>
	<div id='calendar'></div>

</body>
