<div id='cabecera' class="navbar navbar-default navbar-fixed-top" role="navigation">
    <?php echo Html::img('membrete.jpg', 'Membrete','width="100%"'); ?>
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar pull-right" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand">SIGERISA</a>
            <div class="nav-collapse">
                <?php View::renderMenu(Menu::APP) ?>
                <ul class="nav pull-right">
                <li><?php echo Html::link('admin/index', 'Iniciar Sesión / Registro') ?></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<br><br><br><br><br><br>
