<!-- Carousel
    ================================================== -->
<div class="slider-wrapper theme-default">
            <div id="slider" class="nivoSlider">
						<a href=""><?php echo Html::img('banner/cielo.png', 'cielo'); ?></a>
						<a href=""><?php echo Html::img('banner/relax.png', 'relax'); ?></a>
                        <a href=""><?php echo Html::img('banner/verde.png', 'verde'); ?></a>
					</div>
    </div>
    <div class="container">
        <div class="row">
        <div class="span8"><div id="content">.col-md-8</div></div>
        <div class="span4">
            <div class="widget">
                <h4 class="widgettitulo">Denuncias</h4>
                <ul>
                    <li><a href="">Desechos Sólidos</a></li>
                    <li><a href="">Contaminación Ambiental </a></li>
                    <li><a href="">Contaminación Del Agua </a></li>
                </ul>
            </div>
        </div>
        </div>
    </div>
<?php View::content() ?>
    <script type="text/javascript">
    $(window).load(function() {
        $('#slider').nivoSlider();
    });
    </script>
