<div class="page-header">
    <h1><?php eh($titulo) ?></h1>
</div>
<div class="row">
    <div class="span3">
        <?php //View::partial('backend/menus/cargo') ?>
    </div>
    <div class="span8 span-derecho" >
        <div id="res-form-ajax"><?php View::content() ?></div>
        <?php echo Ajax::form('res-form-ajax', NULL, 'form-horizontal') ?>
        <?php //echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
        <?php $persona_id = Auth::get('persona_id');
        echo Form::hidden('solicitud.id');
        echo Form::hidden('solicitud.persona_id', '', $persona_id);?>        
        <?php echo Form::hidden('solicitud.id') ?>
                <div class="control-group">
            <label class="control-label" for="solicitud_tiposolicitud_id">Tipo de Solicitud : </label>
            <div class="controls">
                <?php echo Form::dbSelect('solicitud.tiposolicitud_id', 'nombre', array('tipo_solicitud', 'find'), 'Ninguno') ?>
            </div>
        </div>
        <div id='div_estado'> </div>

        <div class="row control-group">
            <label class="control-label" for="solicitud_nombre">Nombre * : </label>
            <?php echo Form::text('solicitud.nombre', 'class="span4"') ?>
        </div>
        <div class="row control-group">
            <label class="control-label" for="solicitud_observacion">Observación * : </label>
            <?php echo Form::textarea('solicitud.observacion', 'class="span4"') ?>
        </div>
            <div class="form-actions">
            <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
            <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
            </div>
        <?php echo Form::close() ?>
    </div>
</div>
<script type='text/javascript'>
$("#solicitud_tiposolicitud_id").click(function(){
    var tiposolicitud_id     =   $('#solicitud_tiposolicitud_id').val();
        $.ajax({
          type: "POST",
          url: "<?php echo PUBLIC_PATH . 'admin/solicitud/getTiposolicitudCaracteristicas/'; ?>",
          data: "tiposolicitud_id=" + tiposolicitud_id,
          success: function(html){
            $("#div_estado").html(html);
          }
        });
});
</script>