<div class="page-header">
    <h1>Solicitudes</h1>
</div>
<?php View::content() ?>
<?php/*
echo Form::open('admin/cargo/eliminar', 'post', 'class="form_lista"');
View::partial('backend/barra_superior_listas', FALSE, array('texto' => 'Crear Cargo'));
$dt = new DataTable($cargos);
$dt->addHeaders(Form::check('seleccionar_todos', 'todos', NULL, FALSE));
$dt->addHeaders('id', 'Nombre', 'Observación');
$dt->addHeaders('Editar', 'Eliminar');
$dt->check('cargo_id');
$dt->addFields('id', 'nombre', 'observacion');
$dt->imgLink('figuras/editar.png', 'admin/cargo/editar');
$dt->imgLinkConfirm('figuras/eliminar.png', 'admin/cargo/eliminar', '', '¿Realmente desea Eliminar Este Cargo?');
echo $dt->render('class="table table-bordered table-striped"');
echo Form::close();
*/
?>
