<h1 style="margin-bottom: 20px;">Servicios</h1>

<?php View::content() ?>
	<div id="content">
		<article class="post clearfix">
			<br>
			<p><strong>	Le ofrecemos una gran variedad de servicios </strong>  
				
<br><br>*Servicio de control de vectores, reservorios y fauna nociva
<br>*Servicio regional de salud radiológica
<br>*Servicio de epidemiología ambiental
<br>*Residuos sólidos
<br>*Desechos peligrosos
<br>*Construcción y urbanismo
<br>*Contaminación atmosférica
<br>*Aguas residuales y efluentes
<br>*Aguas de abastecimiento y recreación
<br>*Sustancias y materiales peligrosos
<br>*Plaguicidas

</p>

  </div>

<div style="clear: both;"></div>
