<div class="main">

    <div class="container">

      <div class="row">
      	
      	<div class="span6">
      		

			
			<div class="widget widget-nopad stacked">
						
				<div class="widget-header">
					<i class="icon-list-alt"></i>
					<h3>Denuncias</h3>
				</div> <!-- /widget-header -->
				
				<div class="widget-content">
					
					<ul class="news-items">
						<li>
							
							<div class="news-item-detail">										
								<a href="javascript:;" class="news-item-title">Duis aute irure dolor in reprehenderit</a>
								<p class="news-item-preview">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore.</p>
							</div>
							
							<div class="news-item-date">
								<span class="news-item-day">08</span>
								<span class="news-item-month">Mar</span>
							</div>
						</li>
						<li>
							<div class="news-item-detail">										
								<a href="javascript:;" class="news-item-title">Duis aute irure dolor in reprehenderit</a>
								<p class="news-item-preview">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore.</p>
							</div>
							
							<div class="news-item-date">
								<span class="news-item-day">08</span>
								<span class="news-item-month">Mar</span>
							</div>
						</li>
						<li>
							<div class="news-item-detail">										
								<a href="javascript:;" class="news-item-title">Duis aute irure dolor in reprehenderit</a>
								<p class="news-item-preview">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore.</p>
							</div>
							
							<div class="news-item-date">
								<span class="news-item-day">08</span>
								<span class="news-item-month">Mar</span>
							</div>
						</li>
					</ul>
					
				</div> <!-- /widget-content -->
			
			</div> <!-- /widget -->	
					
										
      		
	    </div> <!-- /span6 -->
      	
      	
      	<div class="span6">	
      		
      		

      		
      		
					
					

					
					
					
					
			<div class="widget stacked widget-table action-table">
					
				<div class="widget-header">
					<i class="icon-th-list"></i>
					<h3>Solicitudes</h3>
				</div> <!-- /widget-header -->
				
				<div class="widget-content">
					
					<table class="table table-striped table-bordered">
						<thead>
							<tr>
								<th>Persona</th>
								<th>Solicitud</th>
								<th class="td-actions"></th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>Persona</td>
								<td>Internet
									 Explorer 4.0</td>
								<td class="td-actions">
									<a href="javascript:;" class="btn btn-small btn-warning">
										<i class="btn-icon-only icon-ok"></i>										
									</a>
									
									<a href="javascript:;" class="btn btn-small">
										<i class="btn-icon-only icon-remove"></i>										
									</a>
								</td>
							</tr>
							<tr>
								<td>Persona</td>
								<td>Internet
									 Explorer 5.0</td>
								<td class="td-actions">
									<a href="javascript:;" class="btn btn-small btn-warning">
										<i class="btn-icon-only icon-ok"></i>										
									</a>
									
									<a href="javascript:;" class="btn btn-small">
										<i class="btn-icon-only icon-remove"></i>										
									</a>
								</td>
							</tr>
							<tr>
								<td>Persona</td>
								<td>Solicitud</td>
								<td class="td-actions">
									<a href="javascript:;" class="btn btn-small btn-warning">
										<i class="btn-icon-only icon-ok"></i>										
									</a>
									
									<a href="javascript:;" class="btn btn-small">
										<i class="btn-icon-only icon-remove"></i>										
									</a>
								</td>
							</tr>
							<tr>
								<td>Persona</td>
								<td>Solicitud Catastro</td>
								<td class="td-actions">
									<a href="javascript:;" class="btn btn-small btn-warning">
										<i class="btn-icon-only icon-ok"></i>										
									</a>
									
									<a href="javascript:;" class="btn btn-small">
										<i class="btn-icon-only icon-remove"></i>										
									</a>
								</td>
							</tr>
							<tr>
								<td>Persona</td>
								<td>Solicitud</td>
								<td class="td-actions">
									<a href="javascript:;" class="btn btn-small btn-warning">
										<i class="btn-icon-only icon-ok"></i>										
									</a>
									
									<a href="javascript:;" class="btn btn-small">
										<i class="btn-icon-only icon-remove"></i>										
									</a>
								</td>
							</tr>
							<tr>
								<td>Persona</td>
								<td>Solicitud</td>
								<td class="td-actions">
									<a href="javascript:;" class="btn btn-small btn-warning">
										<i class="btn-icon-only icon-ok"></i>										
									</a>
									
									<a href="javascript:;" class="btn btn-small">
										<i class="btn-icon-only icon-remove"></i>										
									</a>
								</td>
							</tr>
							</tbody>
						</table>
					
				</div> <!-- /widget-content -->
			
			</div> <!-- /widget -->
								
	      </div> <!-- /span6 -->
      	
      </div> <!-- /row -->

    </div> <!-- /container -->
    
</div> <!-- /main -->

<div class="container-fluid dw-shell-view">
    
    <div class="dw-overflow">

     <p>Sesion : <?php // echo var_dump($_SESSION); ?> </p>



    </div>
    
</div>
