<div class="page-header">
    <h1><?php eh($titulo) ?></h1>
</div>
<div class="row">
    <div class="span8" >
        <div id="res-form-ajax"><?php View::content() ?></div>
        <?php echo Ajax::form('res-form-ajax', NULL, 'form-horizontal') ?>
        <?php //echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
        <?php $persona_id = Auth::get('persona_id');
        echo Form::hidden('denuncia.id');?>
        <div class="row control-group">
            <label class="control-label" for="denuncia_nombre">Fecha Asignacion: </label>
            <?php echo Form::text('detalle_denuncia.fecha_asignacion', 'class="span2" readonly', date('d-m-Y') ) ?>
        </div>
         <div class="row control-group">
            <label class="control-label" for="denuncia_nombre">Fecha a Inspeccionar: </label>
            <?php echo Form::date('detalle_denuncia.fecha_inspeccion', 'class="span2 mask-num"') ?>
        </div>
        <div class="row control-group">
            <label class="control-label" for="detalle_denucia_observacion">Empleado a asignar: </label>
            <?php echo Form::dbSelect('detalle_denuncia.empleado_id', 'nombre1', array('empleado', 'getListadoEmpleado'), 'Seleccione:') ?>
        </div>
         <div class="row control-group">
            <label class="control-label" for="detalle_denucia_turno">Turno: </label>
           <?php echo DwForm::select('detalle_denuncia.turno', array(''=>'Seleccione:', 'M'=>'Mañana', 'T'=>'Tarde', 'D'=>'Todo el Dia'), array('class'=>'input-required')); ?>
        </div>
        <div class="row control-group">
            <label class="control-label" for="denuncia_observacion">Observaciones: </label>
            <?php echo Form::textarea('detalle_denuncia.observacion_asignacion', 'class="span4"') ?>
        </div>

        <div class="form-actions">
            <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
            <?php echo Html::linkAction('listado', 'Cancelar', 'class="btn"') ?>
            </div>
        <?php echo Form::close() ?>
    </div>
</div>
