<div class="page-header">
    <h1><?php eh($titulo) ?></h1>
</div>
<div class="row">
    <div class="span8" >
        <div id="res-form-ajax"><?php View::content() ?></div>
        <?php echo Ajax::form('res-form-ajax', NULL, 'form-horizontal') ?>
        <?php //echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
        <?php $persona_id = Auth::get('persona_id');
        echo Form::hidden('denuncia.id');
        echo Form::hidden('denuncia.persona_id', '', $persona_id);?>
        <div class="row control-group">
            <label class="control-label" for="denuncia_nombre">Fecha Denuncia: </label>
            <?php echo Form::text('denuncia.fecha_denuncia', 'class="span4" readonly', date('d-m-Y') ) ?>
        </div>
        <div class="row control-group">
            <label class="control-label" for="denuncia_observacion">Datos del denunciado: </label>
            <?php echo Form::textarea('denuncia.datos_denunciado', 'class="span4"') ?>
        </div>
        <div class="row control-group">
            <label class="control-label" for="denuncia_observacion">Dirección del denunciado: </label>
            <?php echo Form::textarea('denuncia.direccion_denunciado', 'class="span4"') ?>
        </div>
        <div class="row control-group">
            <label class="control-label" for="denuncia_observacion">Planteamineto del Problema:</label>
            <?php echo Form::textarea('denuncia.planteamiento_problema', 'class="span4"') ?>
        </div>

        <div class="form-actions">
            <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
            <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
            </div>
        <?php echo Form::close() ?>
    </div>
</div>
