<div class="page-header">
    <h1><?php eh($titulo) ?></h1>
</div>
<div class="row">
    <div class="span8" >
        <div id="res-form-ajax"><?php View::content() ?></div>
        <?php echo Ajax::form('res-form-ajax', NULL, 'form-horizontal') ?>
        <?php //echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
        <?php $persona_id = Auth::get('persona_id');
        echo Form::hidden('denuncia.id');?>
        <div class="row control-group">
            <label class="control-label" for="denuncia_observacion">Observaciones: </label>
            <?php echo Form::textarea('detalle_denuncia.observacion_inspeccion', 'class="span4"') ?>
        </div>

        <div class="form-actions">
            <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
            <?php echo Html::linkAction('listado', 'Cancelar', 'class="btn"') ?>
            </div>
        <?php echo Form::close() ?>
    </div>
</div>
